### ISSUE TITLE
problems with aria2 jsonrpc interface

### ISSUE THREAD

**Issue by blackhuman** [briandilley/jsonrpc4j#101]
There is a little problem with aria2 jsonrpc interface.
Aria2 jsonrpc define its method all with prefix **aria2**. which like **aira2.addUri**, but i cannot add this dot character to method name. Trying annotation **JsonRpcMethod**(which may only be used for jsonrpc service exposing) don't work neither.
Is there any workaround to sovle this?

**Comment by gaborbernat** [comment]
I would say not at the moment.
