### ISSUE TITLE
Making multiple JSON RPC calls in one request, where at least one throws an exception, causes the resulting response to return an incomplete array

### ISSUE THREAD

**Issue by pdereg** [briandilley/jsonrpc4j#106]
I tried it both with 1.2 and 1.3 releases. Basically, if I make multiple JSON RPC calls in one request and at least one of these calls throws an exception, the resulting HTTP response contains an incomplete JSON array, which is not closed (the closing bracket is missing) - also, the responses from calls after the one that threw aren't present in the array.

Note that it only happens if the error code from a mapped exception is different than 0 - if it's 0 then it all works as expected. I believe this may be caused by the following line: https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/JsonRpcBasicServer.java#L235

**Comment by gaborbernat** [comment]
Yes you are right. will look into this. Please note that the official maintained version has moved too https://github.com/gaborbernat/jsonrpc4j.

**Comment by gaborbernat** [comment]
Fix, https://github.com/briandilley/jsonrpc4j/commit/7522f55c3a247d7abd656b7aa0c409b9872e2295 will be part of 1.3.0 soon.

**Comment by gaborbernat** [comment]
released.
