### ISSUE TITLE
1.3.0 not available on maven central

### ISSUE THREAD

**Issue by vtintillier** [briandilley/jsonrpc4j#114]
1.30 has been released but is not available on Maven Central : https://search.maven.org/#search%7Cga%7C1%7Cjsonrpc4j

Can it be released there?

**Comment by vtintillier** [comment]
(maybe related to moving to Gradle instead of maven ?)

**Comment by gaborbernat** [comment]
yeah, I know, we now release on jcenter, need to add sync channels for maven

**Comment by gaborbernat** [comment]
https://oss.sonatype.org/content/repositories/releases/com/github/briandilley/jsonrpc4j/jsonrpc4j/
