### ISSUE TITLE
Moving to Gradle removed the OSGi metadata

### ISSUE THREAD

**Issue by vtintillier** [briandilley/jsonrpc4j#115]
Can no longer use jsonrpc4j as an OSGi bundle.

Should use https://docs.gradle.org/current/userguide/osgi_plugin.html

**Comment by gaborbernat** [comment]
add this fix with version 1.3.2, can you try it if it works?

**Comment by gaborbernat** [comment]
at :) 
https://bintray.com/gaborbernat/maven/com.github.briandilley.jsonrpc4j%3Ajsonrpc4j/1.3.2/view

**Comment by gaborbernat** [comment]
fix in, https://github.com/briandilley/jsonrpc4j/commit/fdb1fe38ae9c677a2bf924318e43b1f5042c1f72

**Comment by vtintillier** [comment]
the fix is not good.

All those packages:
- org.springframework.*
- org.apache.http.*
- org.aopalliance.intercept
should be optional.

There is a new dependency on org.apache.commons.logging package. At least I removed the only dep on it in #89. Should check why it is back.

The version range on javax.servelt import is too strict. I had fixed that with #90.

**Comment by gaborbernat** [comment]
All those packages are optional, will look into it more deeply, or if you want you can look yourself and send a pull request.

**Comment by gaborbernat** [comment]
As far as using apache log4j, that is my preferred way of doing things, now all java.util.logging has been removed. log4j2 is much easier to handle, config, use.

**Comment by vtintillier** [comment]
OK, but here it is Apache Commons Logging that is imported in addition to log4j : org.apache.commons.logging

I cannot see any reference to it in the sources, so not sure why it appears in the import-package section.

**Comment by vtintillier** [comment]
I can work on this, but I first need to be sure that you will be able to release to Maven Central in the very near future. I cannot use releases from bintray.

**Comment by gaborbernat** [comment]
I do have release rights on Maven Central, would just need to setup release pipeline for that. I would prefer asking a sync from them to JCenter, why can't you use JCenter?

+--- org.springframework:spring-core:4.2.5.RELEASE
|    \--- commons-logging:commons-logging:1.2
It's used by that package.

**Comment by vtintillier** [comment]
All our corporate builds use an internal nexus server, which proxies some official external repositories like maven central.

jcenter/bintray is not available for us to consume.

**Comment by gaborbernat** [comment]
Managed to add manual syncing for JCenter to maven central, see https://oss.sonatype.org/content/repositories/releases/com/github/briandilley/jsonrpc4j/jsonrpc4j/. 

That being said it was harder than needed to be.

**Comment by gaborbernat** [comment]
Is now okay? :)

**Comment by vtintillier** [comment]
I can see 1.3.3-RC0 in Central now. Thanks a lot.
I prepare a PR to fix optional import-package header.

**Comment by gaborbernat** [comment]
released your fixes as 1..4.0; 

https://oss.sonatype.org/content/repositories/releases/com/github/briandilley/jsonrpc4j/jsonrpc4j/

let me know if this works now :+1:

**Comment by vtintillier** [comment]
Just. Perfect.

Thanks a ton! :beer:
