### ISSUE TITLE
1.3.0 requires Java 1.8

### ISSUE THREAD

**Issue by vtintillier** [briandilley/jsonrpc4j#116]
We have

targetCompatibility = 1.8

in build.gradle.

Previous versions only required Java 1.6.

Can it at least be changed to 1.7? Any reason for specifically targetting 1.8?

**Comment by gaborbernat** [comment]
Mostly because Java 7 reached its end of life a year ago, http://www.infoq.com/news/2015/05/Oracle-Ends-Java-7Public-Updates, and I no longer have java 7 versions around to build a java 7 release.
