### ISSUE TITLE
JsonRpcClientException package-private

### ISSUE THREAD

**Issue by dzolo** [briandilley/jsonrpc4j#123]
In 1.2.0 `JsonRpcClientException` was a public class, now it is package-private. I was using this exception to detect whether `JsonRpcClient#readResponse` has failed because the response it self has had contained an error or if the error was raised during parsing of the response.

Can you make it public again? Or there is a better solution to handle this outside the jsonrpc4j package?

Thanks!

**Comment by gaborbernat** [comment]
done and released in 1.4.1.

**Comment by dzolo** [comment]
Thanks!

**Comment by dzolo** [comment]
Will be the 1.4.1 release available in the central Maven repository?

**Comment by gaborbernat** [comment]
It was, is: https://oss.sonatype.org/content/repositories/releases/com/github/briandilley/jsonrpc4j/jsonrpc4j/

**Comment by dzolo** [comment]
Sorry, I was looking for it at: http://mvnrepository.com/artifact/com.github.briandilley.jsonrpc4j/jsonrpc4j
