### ISSUE TITLE
We call getOutputStream too earlier.

### ISSUE THREAD

**Issue by lanxx019** [briandilley/jsonrpc4j#128]
Sorry, I did not get the issue tab before I created the PR. Going to copy and paste my description from PR here:

Inside `JsonRpcBasicServer`, we call servlet's `getOutputStream` before we construct a internal `InputStream`. The problem is if anything happens during the construction time of `InputStream`, the downstream handlers cannot use the output stream any more. We should postpone the time we call `getOutputStream` after we finish constructing the input stream.

**Comment by gaborbernat** [comment]
released with https://bintray.com/gaborbernat/maven/com.github.briandilley.jsonrpc4j%3Ajsonrpc4j/1.4.3/view
