### ISSUE TITLE
ExceptionResolver interface is not public

### ISSUE THREAD

**Issue by santino83** [briandilley/jsonrpc4j#132]
I'm using version 1.4.3 and need to add a custom ExceptionResolver to the JsonRpcClient due to a wrong error format in 3rd party application. I wanted to use "setExceptionResolver" method in JsonRpcClient, but I cannot create a custom resolver as ExceptionResolver interface has package-private scope and it's not public and cannot extended

**Comment by gaborbernat** [comment]
create a pull request to fix that and I'll accept it quickly.

**Comment by gaborbernat** [comment]
released with 1.4.4.
