### ISSUE TITLE
CompositeJsonServiceExporter and JsonServiceExporter are not visible

### ISSUE THREAD

**Issue by jeacott1** [briandilley/jsonrpc4j#140]
Hi All, new to this project,
 I'm not sure how its supposed to be used. neither JsonServiceExporter nor CompositeJsonServiceExporter are public, so cannot be accessed outside of the 
com.googlecode.jsonrpc4j.spring package.

is anyone using this library? how?

**Comment by aplgithub** [comment]
Have a look under "Auto Discovery With Annotations" on the [README.md](https://github.com/briandilley/jsonrpc4j/blob/master/README.md) file.  Does this answer your question?

**Comment by jeacott1** [comment]
I guess it answers it for the autodiscovery use, but higher up in the docs it says 
"Configure your service in spring as you would any other RemoteExporter:"
```
    <bean name="/UserService.json" class="com.googlecode.jsonrpc4j.spring.JsonServiceExporter">
        <property name="service" ref="userService"/>
        <property name="serviceInterface" value="com.mycompany.UserService"/>
    </bean>
```

this just isn't possible. and its the way I'd prefer to configure it actually.

**Comment by matthjes** [comment]
Why were those classes made package-local in the first place? I would really like to have the option to either use annotations or configure it manually using JsonServiceExporter (in my current project I'm loading plugins using `ServiceLoader` and I don't want to add the annotation to the plugin interface).

**Comment by aplgithub** [comment]
I am not too sure why this is package-private; @gaborbernat may be able to answer this question because it seems to have happened in 2658b404ac1f9424436dca8500a40ec06030959a.

**Comment by matthjes** [comment]
Unfortunately the commit message does not mention the reason (and I doubt that this has been done to make cleaner code).
Any possibility to revert those changes? Apart from cloning the repository and fixing this myself.

**Comment by aplgithub** [comment]
Could you lodge a pull-request to change it?

**Comment by gaborbernat** [comment]
@matthjes this was a bug made during that fix, no logical reason :-1:

**Comment by matthjes** [comment]
I've created a pull request that should change the visibility back to public. #176
