### ISSUE TITLE
wrong content-type in response

### ISSUE THREAD

**Issue by mtmmtm9** [briandilley/jsonrpc4j#144]
According to:  https://www.simple-is-better.org/json-rpc/transport_http.html

"Content-Type: MUST be application/json"

jsonrpc4j uses application/json-rpc.
That cannot be changed.

public static final String JSONRPC_CONTENT_TYPE = "application/json-rpc";

Could that be fixed ?

**Comment by aplgithub** [comment]
Can you please take a look at the pull-request #145.  If this solves this problem, can you please close this issue.

**Comment by mtmmtm9** [comment]
Looks like fixed. Thanks!
