### ISSUE TITLE
using it over TCP

### ISSUE THREAD

**Issue by tux-mind** [briandilley/jsonrpc4j#146]
Hi, I'm making a project for my university, where we are forced to use two kind of connections from the presentation layer to the business one: RMI and socket.

As developer I dislike this "back to the old west", but I have to do this project.

So, I'm asking you if is it possible to use this great library with Spring over TCP sockets ( no HTTP ).

thank you in advance :blush:

**Comment by aplgithub** [comment]
Have you had a read through at the top-level [README.md](README.md) file?

**Comment by tux-mind** [comment]
Sorry @aplgithub , it was late and I was very tired :sweat_smile:

**Comment by LouisWayne** [comment]
@tux-mind How do I use TCP sockets? I can't find it
