### ISSUE TITLE
Context propagation (question)

### ISSUE THREAD

**Issue by blvp** [briandilley/jsonrpc4j#153]
Is it possible to send custom http headers, parameters in runtime and expose it on server side?
For example: 
- We have some services already exported with JsonRpcServer;
- We have created JsonRpcClient.

On the  client side we have some kind of user identificator (token, userId, etc).
We want to pass it to server side for logging purposes without passing it as argument for every service call.

I cannot find solution without modifying JsonRpcClient and JsonRpcServer implementation.

**Comment by briandilley** [comment]
see: https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L326

**Comment by blvp** [comment]
Thanks guys!
