### ISSUE TITLE
Allow subclass of JsonRpcHttpClient to supply own "id"

### ISSUE THREAD

**Issue by lordbuddha** [briandilley/jsonrpc4j#154]
It used to be possible in version 1.2 to subclass JsonRpcHttpClient and to allow the client to supply the id for each invocation by overriding the method   

``` java
     public void invoke(String methodName, Object argument, OutputStream ops, String id)
```

While that method is now this and is private

``` java
    private Object invokeAndReadResponse(String methodName, Object argument, Type returnType, OutputStream output, InputStream input, String id)
```

We have specific need (and currently do on 1.2) to be able to specify the id (actually to use a fixed id for caching reasons).   Probably there should be someway to set an id provider for these id's.

I could fork and implement this, if it would be accepted as a feature as opposed to be rejected as being against the spec....

**Comment by mslipper** [comment]
Hi there,

I'm in the process of cleaning up old issues. Since this appears fixed in PR #156, I'm going to close this issue.
