### ISSUE TITLE
Add support for the gzipping of requests

### ISSUE THREAD

**Issue by lordbuddha** [briandilley/jsonrpc4j#155]
It used to be possible in version 1.2, to subclass JsonRpcHttpClient and override the method

``` java
  public Object invoke(
    String methodName, Object argument, Type returnType,
    Map<String, String> extraHeaders)
```

to support the sending of requests gzipped.    Because of scoping changes, it is now impossible to do this.   Namely, the method prepareConnection is now private as is the class HttpException which makes overriding that method not possible.

We have some requests that several MB in size and must have request compression to fit in available bandwidth and successfully did this with version 1.2.

Supporting gzip in requests seems a useful feature to support.

**Comment by cekvenich** [comment]
I assume that server gzip would work, no?

**Comment by mslipper** [comment]
Hi there,

I'm going to close out this issue since it looks like it's been fixed. Please reopen if this isn't the case.
