### ISSUE TITLE
Wrong RPC version value returns

### ISSUE THREAD

**Issue by xupypg** [briandilley/jsonrpc4j#158]
When server in JsonRpcBasicServer::handleRequest catch JsonParseException it generate json response with invalid version (it will be "jsonrpc":"jsonrpc" ).

**Comment by mslipper** [comment]
Hi @xupypg,

I know it's been almost a year since you posted this issue however I've opened a PR to fix it. Mind reviewing when you get the chance? No worries if you're not able to get to it.

**Comment by xupypg** [comment]
Hi,
Yes that is right.
