### ISSUE TITLE
HTTP error codes not returned in v1.5.0

### ISSUE THREAD

**Issue by ArstanWhitebeard** [briandilley/jsonrpc4j#171]
Following an upgrade from 1.4.6 to 1.5.0 our JSON-RPC server (embedded Jetty, no Spring, gzip disabled or enabled) is no longer returning HTTP error codes generated by an HttpStatusCodeProvider. From stepping through with a debugger, what I think is happening is this:

- HttpStatusCodeProvide.getHttpStatusCode returns SC_BAD_REQUEST (for example).
- JsonRpcBasicServer.handleRequest returns this but doesn't yet set it in the response.
- JsonRpcServer.handleRequest0 calls response.setContentLength
- JsonRpcServer.handleRequest0 calls output.write; because the content length is set, this then immediately closes the HttpOutput, which sends the response back to the client with result code 200.
- JsonRpcServer.handle(line 152) then calls response.setStatus, but by now it's too late.

This issue did not occur on 1.4.6, which did not set the content length and therefore did not close the HttpOutput when it called output.write, meaning that the response was sent back to the client later.

This is a deal-breaker for us and we will downgrade back to 1.4.6 until it is resolved.

**Comment by yin** [comment]
Hi, This bug came in with addition of SSL support, so that has to be rewritten. Is there a particular reason you need 1.5.0?

**Comment by ArstanWhitebeard** [comment]
Thanks for the reply. No particular reason for needing 1.5.0, we picked this up on a routine upgrade of our dependencies, we're OK on 1.4.6 for the time being, but once this is fixed we'd prefer to keep up to date.

**Comment by mslipper** [comment]
This is fixed in `3e2fcb7.` Closing for now. Please reopen if you have any issues.
