### ISSUE TITLE
findCandidateMethods should ignore java method name if JsonRpcMethod is used

### ISSUE THREAD

**Issue by serranom** [briandilley/jsonrpc4j#179]
If a method is annotated with JsonRpcMethod, it seems that the findCandidateMethods method should not consider the original name as a match.  The user has indicated that a different method name is desired for exposure.  I ran into this issue when trying to use JsonRpcMethod to resolve an overloaded match on a single parameter obejct overloaded method.

Happy to submit a PR if you agree with the behavior change.

**Comment by serranom** [comment]
After looking at the tests, I would add a flag that would optionally trigger this behavior to preserve backwards compatibility.

**Comment by gaborbernat** [comment]
I agree, go ahead and create the PR.

**Comment by mslipper** [comment]
Hi @serranom,

I'm going to close this since your PR is both merged and in the latest release.
