### ISSUE TITLE
When might the next official release be?

### ISSUE THREAD

**Issue by serranom** [briandilley/jsonrpc4j#183]
I've contributed a feature (#179) and am wondering when it might be present in a release.  I'm going to be using the feature in an upcoming release of my own so I'd rather not use a personal build.  I'm just curious what the process  is and when releases are planned.

**Comment by gaborbernat** [comment]
The project is sort of abandoned. I no longer use it. You would need to pick up with @briandilley.

**Comment by mslipper** [comment]
@gaborbernat which project did you switch to (assuming you still maintain a JSON-RPC API)?

I'm also happy to help maintain this project should there be a defined roadmap.

**Comment by gaborbernat** [comment]
@mslipper I no longer maintain a JSON-RPC API 👍 No clear roadmap, and you'd need to be blessed access by @briandilley

**Comment by mslipper** [comment]
Got it. I'll reach out to him. Thanks Gabor!

**Comment by mslipper** [comment]
@serranom I contacted @briandilley and was granted write access. I should be able to bump a release shortly. Before I do so, however, I need to bring myself up to speed with what's changed since the last release.

@gaborbernat - do you have some time to help me with that process? A brain-dump from you would be immensely helpful to me.

**Comment by mslipper** [comment]
@serranom I'll bump the release this weekend pending my ability to access Maven central for this project.

**Comment by serranom** [comment]
Thanks!

**Comment by mslipper** [comment]
Quick update @tinchou @serranom - was able to tag the release this past weekend but still need to get access to OSSRH to publish a release.

**Comment by mslipper** [comment]
Version 1.5.1 is released: https://search.maven.org/#artifactdetails%7Ccom.github.briandilley.jsonrpc4j%7Cjsonrpc4j%7C1.5.1%7Cjar. Please open an issue if you have any questions or concerns :).
