### ISSUE TITLE
NPE on using result of getErrorStream()

### ISSUE THREAD

**Issue by mrezin** [briandilley/jsonrpc4j#187]
https://github.com/briandilley/jsonrpc4j/blob/7d480296a6dd44928a5ef1e16c222bc59a5d014d/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L154

This line throws NPE because java.net.HttpURLConnection.getErrorStream() returns null.

**Comment by mslipper** [comment]
Will take a look at this tonight.

**Comment by mslipper** [comment]
Hi @mrezin,

Can you please provide some reproduction steps for this issue?

**Comment by mrezin** [comment]
It happens went client receives timeout exception. 
`private  int readTimeoutMillis = 60 * 1000 * 2;`

Steps to reproduce:
1. Establish connection to the server
2. Suspend corresponding thread on the server
3. Invoke method and wait for the timeout (java.io.IOException: Connection timed out)
4. Catch (IOException) block calls getErrorStream() and receives **null** which leads to NPE

**Comment by mslipper** [comment]
Got it, thanks. Should have a PR out later this evening.

**Comment by mslipper** [comment]
@mrezin PR up. Thanks for finding this.

**Comment by mrezin** [comment]
Sure, I'd be happy to review the PR
