### ISSUE TITLE
Validating arguments

### ISSUE THREAD

**Issue by blackcat** [briandilley/jsonrpc4j#189]
Hello!

I have a need to validate arguments of my jsonrpc service. Now only way is to write validation by hand and throw exception in case validation fails. It's very far from best practices =) What about adding validation mechanism in this library? 
I can do it myself (and crete pull request), but maybe someone already did it?

**Comment by blackcat** [comment]
@mslipper it looks like you is the most active user here =)

**Comment by kostapc** [comment]
@blackcat, I did validation of request body for digital signature by overriding server class, reading input, validate and pass new steam to library.
I can't provide this code because it specific to my problem, but with this idea you can pass raw json to any json-schema validator before parsing.

**Comment by blackcat** [comment]
In my case I need to validate parsed object. But your point is a good place for me to start. Which method have you overrided?

**Comment by mslipper** [comment]
@blackcat will review when I get home tonight.

**Comment by kostapc** [comment]
@blackcat here some example how to inject custom code in server. But bad point is in necessary to copy original code of handle. If you want current hardwired code can be also fixed to provide ability to create custom "preprocessors"

`
public class CustomHandlerServer extends JsonRpcServer {
    public CustomHandlerServer(ObjectMapper mapper, Object handler, Class<?> remoteInterface, boolean gzipResponses) {
        super(mapper, handler, remoteInterface, gzipResponses);
    }

    @Override
    public void handle(HttpServletRequest request, HttpServletResponse response) throws IOException {
        //InputStream input = getRequestStream(request);
        BufferedInputStream bis = new BufferedInputStream(request.getInputStream());
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        int result = bis.read();
        while(result != -1) {
            buf.write((byte) result);
            result = bis.read();
        }

        String encoding = request.getHeader(CONTENT_ENCODING);
        String requestText = buf.toString(encoding);

        // ----------------
        // TODO: check or do whatever with request text!
        // ----------------

        InputStream newInputStream = new ByteArrayInputStream(requestText.getBytes());

        OutputStream output = response.getOutputStream();
        handleRequest(newInputStream, output);
    }
}
`

**Comment by blackcat** [comment]
Thank you! Trying to adapt this code for my needs...

**Comment by blackcat** [comment]
Bingo! I've found com.googlecode.jsonrpc4j.RequestInterceptor!
But it is not bound anywhere...

**Comment by kostapc** [comment]
looks like _com.googlecode.jsonrpc4j_ is parent or fork of this project...

**Comment by mslipper** [comment]
`com.googlecode.jsonrpc4j` is the project that this one was extracted from, I believe. Re: RequestInterceptor - I'll need to make some code changes to expose the `setRequestInterceptor` method on `JsonRpcBasicServer`. I can likely do that this weekend - or, if you need this earlier than that, I'd welcome a PR.

**Comment by blackcat** [comment]
https://github.com/briandilley/jsonrpc4j/pull/190/files

@mslipper ;)

**Comment by mslipper** [comment]
@blackcat you rock! Will take a look tonight when I get home from work.

**Comment by blackcat** [comment]
Sorry, failed to add proper way to set interceptors with Spring. Should take one more evening and pair cups of tea.

**Comment by mslipper** [comment]
Works for me! I'll be here 😄

**Comment by mslipper** [comment]
Merged in PR #190. Will put into next release. Closing for now, please reopen if you have any questions.
