### ISSUE TITLE
set the url path for server

### ISSUE THREAD

**Issue by grimace** [briandilley/jsonrpc4j#194]
I'm trying to use a JsonRpcServer in an android project.   I can't change the client and the client is calling with a path of /jsonrpc.      How do I set the the path for the handler in JsonRpcServer?

**Comment by mslipper** [comment]
Hi @grimace,

You should be able to annotate your handler with `@JsonRpcService("<your path here>")`. Is this what you're looking for?

**Comment by grimace** [comment]
I'll give that a try, thanks.

**Comment by mslipper** [comment]
Hi @grimace,

Did this work for you?

**Comment by grimace** [comment]
This did work!
