### ISSUE TITLE
How to use jsonrpc4j with CA certificate?

### ISSUE THREAD

**Issue by FantasyLions** [briandilley/jsonrpc4j#204]
I need a third-party docking interface is to use the HTTPS, also need to configure a CA certificate.How should be if use jsonrpc4j configuration?

Someone can help me? thank you

**Comment by mslipper** [comment]
Hi @FantasyLions,

I can take a look tonight and get back to you. I'm not sure off the of of my head.

**Comment by FantasyLions** [comment]
@mslipper Thanks!

**Comment by mslipper** [comment]
@FantasyLions you should be able to configure a new CA certificate using Java's `keystore` mechanism. Is there any additional processing that you need to do beyond simply accepting requests signed by the docking interface's CA?

**Comment by fantasylion** [comment]
@XieWeiZM Just do it as mslipper said.
