### ISSUE TITLE
How to configure failover by jsonrpc4j.

### ISSUE THREAD

**Issue by FantasyLions** [briandilley/jsonrpc4j#206]
Hi @mslipper 
      Thank you for all your help before.
      Now I have a another question. I have two server URL, this one is the standby server。How do I configure these two URL.
      

Thanks

**Comment by mslipper** [comment]
Hi @FantasyLions,

Are these servers providing the JSONRPC service or are these failover JSONRPC clients?

**Comment by FantasyLions** [comment]
@mslipper 
Is providing the JSONRPC service.

**Comment by mslipper** [comment]
Understood. If that's the case then I'd recommend using something like nginx as a load balancer. Failover is a bit outside the scope of this project.
