### ISSUE TITLE
Response error body

### ISSUE THREAD

**Issue by thalysgomes-kreditech** [briandilley/jsonrpc4j#234]
Is there anything i can do to use jsonrpc4j and receive errors with this body?:
`{"code":3000,"description":"Invalid request ID","details":null}`

Now I'm getting a NPE from **com.googlecode.jsonrpc4j.DefaultExceptionResolver#createJsonRpcClientException,** this method requere the **message** field and my response body is **description** field.
I understood that this is the specification field but is there anything I can do to workaround this?
I can't change the third party API server

**Comment by briandilley** [comment]
Yes, define your own `ExceptionResolver`
