### ISSUE TITLE
Gzip compression: Should not expect 'Accept-Encoding' to exactly equal 'gzip'

### ISSUE THREAD

**Issue by sumitsharma0999** [briandilley/jsonrpc4j#242]
The `Accept-Encoding` header is a forbidden header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) i.e. it cannot be modified programmatically and it's value is set by the browsers. Chrome and Firefox set it's value to `gzip, defate` which denotes that it can understand both `gzip` **and** `deflate`.

In `JsonRpcServer.java` (), we expect the Accept-Encoding to be exactly equal `gzip`. IMO we should have a more relaxed check here (i.e. we should check if **any** of the specified encoding is `gzip`, instead of checking that it should be **the only** one.

I can take up fixing it if you agree on the issue and the fix.

**Comment by briandilley** [comment]
Feel free to submit a patch.
