### ISSUE TITLE
Exception does not propegate to the client from the server (InvocationTargetException)

### ISSUE THREAD

**Issue by gaborbernat** [briandilley/jsonrpc4j#33]
When I throw a RuntimeException from the server it does not fully extract the source exception and such sends an InvocationTargetException to the client. However, this cannot be instantianated, so the client throws:

     WARNING: Unable to find a suitable constructor for        java.lang.reflect.InvocationTargetException
     Exception in thread "main" com.googlecode.jsonrpc4j.JsonRpcClientException: null
        at        com.googlecode.jsonrpc4j.DefaultExceptionResolver.createJsonRpcClientException(DefaultExceptionResolver.java:80)

Here's a quick test project (https://github.com/gaborbernat/json4j-rpc-test). You need to run:

./gradlew server:appRun 
./gradlew client:run

Any ideas what's wrong and how to fix it?

Thanks,

**Comment by folsson** [comment]
I would also love to see this patch merged to upstream.
@bgaborg, I think that @briandilley is waiting for you to actually create the pull request?

**Comment by folsson** [comment]
@briandilley, any progress on this?

**Comment by gaborbernat** [comment]
This has been merged in. Unfortunatly no release since then, but around the end of the month I'll aim for a new release (1.2.0?).

**Comment by folsson** [comment]
Awesome!
