### ISSUE TITLE
JSON-RPC GET handling has an extra URL decode on params

### ISSUE THREAD

**Issue by ByronWLong** [briandilley/jsonrpc4j#44]
When the params for a JSON-RPC request are URL encoded, the are Base64 encoded, and the URL encoded to make the Base64 URL safe (see http://jsonrpc.org/historical/json-rpc-over-http.html#encoded-parameters). In JsonRpcServer.createInputStream, the params argument has already been URL decoded, and then it is converted from Base64 to a String, however, that string is then URL decoded again. This causes any URL unsafe characters in the params to be changed, corrupting the params. I've attached a patch in the next comment (hopefully)

**Comment by gaborbernat** [comment]
@ByronWLong  Can you post that patch?

**Comment by gaborbernat** [comment]
could not replicate, closing it for now.
