### ISSUE TITLE
JSON RPC over Spring RestTemplate

### ISSUE THREAD

**Issue by im-scooter** [briandilley/jsonrpc4j#67]
Hi!
How about to add implementation using Spring RestTemplate as mapping and transport layer for requests?

Yours respectfully,  Toha.

**Comment by briandilley** [comment]
Sure

**Comment by im-scooter** [comment]
So may I add  this functionality to project?

**Comment by gaborbernat** [comment]
Do you have a pull request for this?

**Comment by im-scooter** [comment]
No, I need a pull request.

**Comment by gaborbernat** [comment]
The pull request should be done by you, once you have implemented it.

**Comment by im-scooter** [comment]
Do I have got right  that I should to fork project, make changes and then create a pull request?

**Comment by gaborbernat** [comment]
Yes :)
