### ISSUE TITLE
Doggie contrstuctor

### ISSUE THREAD

**Issue by davidnewcomb** [briandilley/jsonrpc4j#68]
in version 1.1

	/**
	 * Creates the server with a default {@link ObjectMapper} delegating
	 * all calls to the given {@code handler} {@link Object} but only
	 * methods available on the {@code remoteInterface}.
	 *
	 * @param handler the {@code handler}
	 * @param remoteInterface the interface
	 */
	public JsonRpcServer(Object handler, Class<?> remoteInterface) {
		this(new ObjectMapper(), handler, null);
	}

Is this right? remoteInterface isn't being used! Surely this should be:

	public JsonRpcServer(Object handler, Class<?> remoteInterface) {
		this(new ObjectMapper(), handler, remoteInterface);
	}

otherwise what's the point of passing remoteInterface?

**Comment by wuwen5** [comment]
Yes
fix in
https://github.com/briandilley/jsonrpc4j/commit/db383f114a359e7c01681f68a43b414b067a6e10

**Comment by gaborbernat** [comment]
@wuwen5 can you create a pull request for this :)

**Comment by wuwen5** [comment]
@davidnewcomb @gaborbernat this problem has been merged :)
https://github.com/briandilley/jsonrpc4j/commit/419e83a12c75444f674288cacfcc0dc920540551
