### ISSUE TITLE
1.2 release

### ISSUE THREAD

**Issue by vtintillier** [briandilley/jsonrpc4j#71]
Is there any planned date for 1.2 release?
Also in commit dcddedf, version was changed from 1.2-SNAPSHOT to 1.2.1-SNAPSHOT, so it is not clear if 1.2/1.2.0 was supposed to be released.

Thanks

**Comment by gaborbernat** [comment]
Hello, 

That's a bug. We're still preparing for release 1.2.0. Probably sometime during the next month :) 

Thanks,

**Comment by vtintillier** [comment]
Thanks
