### ISSUE TITLE
Incorrect HTTP Status code for error requests

### ISSUE THREAD

**Issue by LeeU1911** [briandilley/jsonrpc4j#72]
I've used jsonrpc4j for my recent project. During that I found out it didn't send correct HTTP Status code for error requests such as "Parse error" or "Method not found" as listed in this table:
http://www.jsonrpc.org/historical/json-rpc-over-http.html#errors

Although the json response has error code and message correctly, the HTTP status code is always 200 - OK in those case.

**Comment by gaborbernat** [comment]
Thanks for the report, we'll investigate it.

**Comment by LeeU1911** [comment]
I have done a fix for this basically by not flushing the output in JsonRpcClient.writeAndFlushValue() but to flush it outside of this method so that I can set the HTTP status code correctly. Only then, the response is flushed. 

Additionally, JsonRpcServer.handle(HttpServletRequest request, HttpServletResponse response) method is added with code checking return code from method handle(InputStream is, OutputStream os) to properly set the HTTP status code. 

Note that return type of JsonRpcBasicServer.handle(InputStream is, OutputStream os) and its children methods are changed from 'void' to 'int' to return the error code in case of error, 0 if successful.

I will commit the code change for review tomorrow.

**Comment by LeeU1911** [comment]
Committed fix and created pull request #73
