### ISSUE TITLE
Include OSGi metadata in the manifest for 1.2 release

### ISSUE THREAD

**Issue by vtintillier** [briandilley/jsonrpc4j#74]
#11 added OSGi metadata in the manifest before 1.1 release.
But #13 moved the maven configuration in a new profile.

As a result 1.1 was released without any OSGi metadata in the manifest.

Any idea why this was moved to a profile?
Can we fix this for 1.2?

I can help, but for that I first need to know what command is run to generate a release version. Any place where this is documented? Can I just remove the shaded-bundle profile and provide just OSGi manifest generation?

Thanks

**Comment by gaborbernat** [comment]
Hello, 

At the moment Brian has no availability to assist with this project. As such, I've contacted him and managed to convince him to give me contributor rights. As such I think I'm the only active maintainer at the moment. I'm still not fully familiar with the project, but I plan to analyze it completely in the next weeks. After this I'll take a look on this,  so bear with me in the meantime. 

Thanks,

**Comment by gaborbernat** [comment]
will try to make a release sometime during the next week :smile:
