### ISSUE TITLE
Compiler time error while using JsonRpcServer with HttpServletRequest and HttpServletResponse 

### ISSUE THREAD

**Issue by vishalzanzrukia** [briandilley/jsonrpc4j#76]
I am using jsonrpc4j 1.1 using following dependency with maven.

```xml
<dependency>
     <groupId>com.github.briandilley.jsonrpc4j</groupId>
     <artifactId>jsonrpc4j</artifactId>
     <version>1.1</version>
</dependency>
```

And I am writing simple Servlet to create `JsonRpcServer` as follows.

```java
@WebServlet
public class SampleServer extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Service service;
    private JsonRpcServer jsonRpcServer;

	
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) {
        jsonRpcServer.handle(req, resp);
    }

	public void init(ServletConfig config) {
        this.service = new Service();
        this.jsonRpcServer = new JsonRpcServer(this.service, ServiceInterface.class);
    }
}
```
I know that jsonRpcServer have this method.

```java
public void handle(HttpServletRequest request, HttpServletResponse response){
...
}
```

even though I am getting compile time error in eclipse which says,
`The type javax.portlet.ResourceResponse cannot be resolved. It is indirectly referenced from required .class files`
![json-rpc-eclipse-error](https://cloud.githubusercontent.com/assets/5804400/9174038/61eb4254-3f9b-11e5-99d8-7eb0a61def71.png)

 I have servlet api in my eclipse classpath, second thing I am not using anywhere `javax.portlet.ResourceResponse`. 

I have also searched a lot on Google, but can't find any answer. Is this bug? Can anybody help me. Any help would be very appreciated.

Thanks in advance.

Regards,
Vishal Z.

**Comment by wuwen5** [comment]
Maybe you need
```xml
 <dependency>
     <groupId>javax.portlet</groupId>
     <artifactId>portlet-api</artifactId>
     <version>2.0</version>
     <optional>true</optional>
     <scope>provided</scope>
</dependency>
```

**Comment by vishalzanzrukia** [comment]
Yes, I am able to resolve this error using this solution, but any idea why this is required? I am not using portlet. Does not seem like annoying?

**Comment by edisontest** [comment]
good

**Comment by snegtec** [comment]
You can use "portlet-api_2.0_spec-1.0.jar" from Pluto (a portlet container). Just copy to WEB-INF/lib and correctly Configure Build Path.
