### ISSUE TITLE
Impossible to choose which exceptions to log

### ISSUE THREAD

**Issue by davidnewcomb** [briandilley/jsonrpc4j#77]
In JsonRpcBasicServer.java the following code appears at the end of handleObject()

	// log and potentially re-throw errors
		if (thrown!=null) {
			if (LOGGER.isLoggable(exceptionLogLevel)) {
				LOGGER.log(exceptionLogLevel, "Error in JSON-RPC Service", thrown);
			}
			if (rethrowExceptions) {
				throw new RuntimeException(thrown);
			}
		}
		return returnCode;
	}

This means that the jsonrpc is constantly logging exceptions that no one cares about. As a result there is no way to tell it not to fill the log with exceptions other than switching off all log messages for that log level which is not sensible as you need some of them.

Can you throw the exception upwards so we can decide whether to log it.

// log and potentially re-throw errors
		if (thrown!=null) {
			if (rethrowExceptions) {
				throw new RuntimeException(thrown);
			}
		}
		return returnCode;
	}

**Comment by aplgithub** [comment]
Hi @davidnewcomb; another approach is to set the "exceptionLogLevel" to "Level.OFF" and then to implement "InvocationListener" to listen to what happened during an invocation and to handle logging there.  Would this satisfy your requirements?

**Comment by davidnewcomb** [comment]
Thanks, I'll try that and let you know.

**Comment by davidnewcomb** [comment]
The project I'm on has finished and I never got to try this but I'm sure it would have been fine ;)
