### ISSUE TITLE
Avoid chunked encoding by calling setContentLength() before writing to output stream

### ISSUE THREAD

**Issue by msgilligan** [briandilley/jsonrpc4j#80]
I'm working on a Java-based JSON RPC server that will be compatible with the **Bitcoin Core** JSON RPC implementation. The command line client `bitcoin-cli` is the canonical Bitcoin RPC client and returns `error: no response from server` when talking to my server based on **jsonrpc4j**.

I spent some time debugging and determined that `bitcoin-cli` can't handle an HTTP chunked response.

I changed:

    int result = handle(input, output);

to:
 
    ByteArrayOutputStream bufOut = new ByteArrayOutputStream(1024);
    int result = handle(input, bufOut);
    response.setContentLength(bufOut.size());	// Set content-length avoid chunked encoding
    output.write(bufOut.toByteArray());

in `JsonRpcServer.java` and that solved the problem.

Should we make a change like the above to completely disable chunked encoding or should we make it configurable? I'd love to see this fix go in to 1.2.0 and am willing to submit a pull request once we agree on the right way to solve the problem.

**Comment by msgilligan** [comment]
For reference I also opened an issue on Bitcoin: https://github.com/bitcoin/bitcoin/issues/6623

**Comment by gaborbernat** [comment]
Hmm, we can look into it. I've been trying to get hold of the owner of this package for making a new release, no luck upto this point. Maybe I'll release it under a different name eventually :)

**Comment by msgilligan** [comment]
I see in the repo there is a 1.2.0-rc1 version, so is a 1.2 release almost ready?

It also looks like you have commit access. What else do you need to make a release? (JAR publishing, etc.)

I may be willing to help out (at a minimum with a fix for this issue) as I'm starting a project to build an (eventually) complete Java reimplementation of the [Bitcoin Core JSON-RPC API](https://bitcoin.org/en/developer-reference#rpcs)

**Comment by gaborbernat** [comment]
I can commit, accept pulls requests, however I do not have access to
publish new versions to Maven Central.

On 9/3/15, Sean Gilligan <notifications@github.com> wrote:
> I see in the repo there is a 1.2.0-rc1 version, so is a 1.2 release almost
> ready?
>
> It also looks like you have commit access. What else do you need to make a
> release? (JAR publishing, etc.)
>
> I may be willing to help out (at a minimum with a fix for this issue) as I'm
> starting a project to build an (eventually) complete Java reimplementation
> of the [Bitcoin Core JSON-RPC
> API](https://bitcoin.org/en/developer-reference#rpcs)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/briandilley/jsonrpc4j/issues/80#issuecomment-137358278


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by msgilligan** [comment]
How long have you been trying to contact the owner?

**Comment by gaborbernat** [comment]
A month or so :)

**Comment by msgilligan** [comment]
Well August is vacation month for a lot of people, plus for parents school is just starting and that is always hectic. Monday, Sept 7th is the U.S. Labor Day holiday and people's schedules get back to normal after that. Let's give him a few more weeks to respond. How soon will you be ready to release?  (Assuming I get  a fix for this bug to you)

I assume it is @briandilley that you're talking about. Let me know if you wan't me to help contact him. (Besides tagging him in this comment.)

**Comment by gaborbernat** [comment]
You are right :)

Bernát GÁBOR

**Comment by msgilligan** [comment]
Note that https://github.com/bitcoin/bitcoin/issues/6623 is now closed and a fix has been committed to `master` for Bitcoin. I'm not sure it will be released and older clients will still have the issue.

**Comment by msgilligan** [comment]
@gaborbernat why did you close this issue?

**Comment by gaborbernat** [comment]
Thought we have resolved this :thought_balloon:

**Comment by gaborbernat** [comment]
I would make it configurable, if you make a patch we can still put this into 1.2.0

**Comment by msgilligan** [comment]
Well, there's an (unreleased) fix for **Bitcoin Core** that resolves the issue for my use case, so it's a lower priority for me now. But I think this should still be configurable in **json4rpc**.

I have some code which fixes the issue in **json4rpc** but it is not configurable, yet. My suggestion is to keep the issue open, but not assign it to the 1.2.0 release.

**Comment by gaborbernat** [comment]
done.
