### ISSUE TITLE
release current HEAD as 1.2.1

### ISSUE THREAD

**Issue by gaborbernat** [briandilley/jsonrpc4j#91]
@vtintillier 

"My understanding by reading [1] and [2]:

you need Brian's Sonatype credentials, can be recovered at [3]
you need the GPG key passphrase. If this is lost, I guess a new GPG key can be uploaded again following [2]
On a side note, it may be worth automating all this using Rultor, see [4].

If we want to include this PR in the release, we have to change back the version from 1.3.0-SNAPSHOT to 1.2.0 however, as master currently looks like 1.2.0 is already released.

[1] http://central.sonatype.org/pages/apache-maven.html
[2] http://central.sonatype.org/pages/working-with-pgp-signatures.html
[3] https://issues.sonatype.org/secure/ForgotLoginDetails.jspa
[4] http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html"

**Comment by vtintillier** [comment]
Hello @gaborbernat  and @briandilley 

is anything blocking the release? Can I help with anything?

Thanks

**Comment by gaborbernat** [comment]
Hello, 

So actually it turns out somebody already made the release, see:

http://mvnrepository.com/artifact/com.github.briandilley.jsonrpc4j/jsonrpc4j/1.2.0

At the moment my hands are full with the holidays and some interviewing, so could not verify it yet, that it's good from myself. Hence, not closing this ticket yet.

**Comment by vtintillier** [comment]
Looking at the pom in the relased jar, I guess @briandilley released with commit 6dcf831807d9a5a0827946244257ed12f982552f

Can we release 1.2.1 that would include 896610876a4fb6acbbb188e483a400995420a9b2 ?

Thanks

**Comment by gaborbernat** [comment]
will try to contact @briandilley for this, thanks.

**Comment by briandilley** [comment]
I'm here :)  What do you need released?  And how can we make it so I don't have to do the releases.

**Comment by gaborbernat** [comment]
Basically the latest head :+1: . 
Are you doing releases via Sonatatype OSS ?

**Comment by gaborbernat** [comment]
@briandilley ? :)

**Comment by vtintillier** [comment]
Hello @briandilley, when can we expect this 1.2.1 release? Do you need any help?

**Comment by gaborbernat** [comment]
@briandilley I am still awaiting for you to provide release access for me on this; also I would like to add Travis integration to the project and make the release pipeline automatically.

**Comment by vtintillier** [comment]
Hi @gaborbernat 

I was full of hope when I saw a 1.3.0 release, but I have issues with it, see #114 and #115.
Do you have full release rights now, i.e if I fix #115 you will be able to release a 1.3.1 version in a few days, including releasing to Maven Central?

I need to know if
- I should invest in fixing the OSGi stuff
- or rather release a 1.2.1 with maven with your help
- or rather release an internal fork in my company

We now urgently need a release that includes the OSGi manifest for our product release :-(

Thanks
Vivien

**Comment by gaborbernat** [comment]
I can release now, but moved to JCenter (planing to add sync to maven central), we should fix the Gradle release for OSGI.
