### ISSUE TITLE
Better support for laziness

### ISSUE THREAD

**Issue by KintaroBC** [briandilley/jsonrpc4j#93]
This is a feature request.

I want the project to better support my laziness. I am just an intermediate Java programmer who wants to use this library. I am used to doing that with jar archives of the library. Nearly every other project I use releases JAR archives.

It is much easier, as it is I have to work out how to compile a jar with maven. I barely understand Maven, so this has put a hurdle in the way of my timeline. It would be nice if you guys could consider the needs of your average programmer.

**Comment by gaborbernat** [comment]
fixed by https://github.com/briandilley/jsonrpc4j/commit/399ce902c4b0a1979d03a62b5cc6c2d1cc173a3c
